kind: wasmer.io/App.v0
name: batik-mock
description: Batik Nusantara storefront (Laravel + MySQL) on Wasmer Edge
package: batik-mock/batik-mock

env:
  APP_ENV: production
  APP_DEBUG: "false"
  APP_URL: "https://batik-mock.wasmer.app"

capabilities:
  database:
    engine: mysql

locality:
  regions:
    - fr-roub1

scaling:
  mode: single_concurrency

jobs:
  - name: migrate-db
    trigger: post-deployment
    action:
      execute:
        command: php
        cli_args: ["artisan", "migrate", "--seed", "--force"]
        timeout: 5m