kind: wasmer.io/App.v0
name: batik-nusantara-rw
description: Batik Nusantara storefront (Laravel + MySQL) on Wasmer Edge
package: batik-nusantara-rw/batik-nusantara-rw

env:
  APP_ENV: production
  APP_DEBUG: "false"
  APP_URL: "https://batik-nusantara-rw.wasmer.app"

capabilities:
  database:
    engine: mysql

locality:
  regions:
    - fr-roub1

scaling:
  mode: single_concurrency
